# serverless.yml
service: flask-based-single-handler

provider:
  naem: aws
  runtime: 3.8
  region: ap-northeast-1
  stage: dev
  memorySize: 128

plugins:
  - serverless-wsgi
  - serverless-python-requirements

custom:
  wsgi:
    app: app.app
    packRequirements: false
  functions:
    app:
      handler: wsgi.handler
      events:
        - http: ANY /
        - http: 'ANY {proxy+}'